### ISSUE TITLE
Binaries and Changelog

### ISSUE THREAD

**Issue by lucy2812** [Telios-org/email-client-desktop#47]
Can we get released binaries and a change log?
This will also help receiving notifications of new releases/betas and changes.
Thank you.

**Comment by hexadecible** [comment]
Yes, we'll be adding change logs going forward after our next release in a couple of weeks. We'll work on getting the binaries hosted on our website as they're currently built in GitLab.

**Comment by hexadecible** [comment]
Changelog and binaries have been added for 0.8.0 and will keep doing so going forward.
