### ISSUE TITLE
Login Attempt - ELOCKED: File is locked

### ISSUE THREAD

**Issue by zacharytyhacz** [Telios-org/email-client-desktop#63]
Device: MacOS Monterey 12.2 M1
Telios Version: 0.8.529

- I exited Telios by clicking red x to close on Mac window frame
- Telios was still 'open' ( or running, still open at my bottom apps bar ), so I went to the top left bar and went Telios -> Quit
- Opened Telios back up and attempted login with correct password
- Error appears, unsure meaning / how to fix / what to do

<img width="404" alt="image" src="https://user-images.githubusercontent.com/38140593/172875485-29284d8c-c30c-4b04-ad25-a923dcb16a0f.png">

**Comment by ynnelson** [comment]
@zacharytyhacz is this still happening on the latest build?

**Comment by zacharytyhacz** [comment]
> @zacharytyhacz is this still happening on the latest build?

I will update and retry later, thanks @ynnelson 

I will mention that I was able to restart my Mac and log back into Telios

**Comment by zacharytyhacz** [comment]
@ynnelson I am trying to recreate the issue now on latest version `0.8.545`, but it doesn't seem to be happening anymore - when I close Telios it fully closes and I can reopen + login without any issues

Thanks @ynnelson  , closing
