### ISSUE TITLE
Green checkbox is misaligned when selecting your Telios email address.

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/email-client-desktop#73]
### Description

Green checkbox is misaligned when selecting your Telios email address.

### Steps to reproduce

1. Select create new account
2. On step two, enter a valid Telios email address

### Screenshots / Videos / Additional Details
![Screen Shot 2022-09-06 at 12 37 33 PM](https://user-images.githubusercontent.com/63071090/188689955-91451a0b-e61f-42f3-8523-c7d0df9f24b9.png)

**Comment by ynnelson** [comment]
Fixed!
