### ISSUE TITLE
Unable to see time to crack password after "Seconds"

### ISSUE THREAD

**Issue by hexadecible** [Telios-org/email-client-desktop#74]
### Description

After entering in a master password, the time to crack display goes white after the time to crack goes above "Seconds"

### Steps to reproduce

1. Create a new account and go to the master password step
2. Enter a password that takes longer than seconds to crack
3. Time to crack does not display/displays all white

### Environment details

Operating System + Hardware details: e.g. 2020 MacBook Pro M1
Telios Version: _See the bottom left of the login screen_

### Expected behavior

Time to crack should go from red -> orange -> yellow -> green

### Screenshots / Videos / Additional Details
![Screen Shot 2022-09-06 at 12 51 22 PM](https://user-images.githubusercontent.com/63071090/188695025-e01d8a70-ad7f-4083-981a-08564344e9ec.png)

**Comment by ynnelson** [comment]
Fixed, the tailwind.config.js file was not compile the classes in the utils folder, added it to the config file and now the colors show up just fine.
