### ISSUE TITLE
Can't save Display Name or Avatart

### ISSUE THREAD

**Issue by ynnelson** [Telios-org/email-client-desktop#80]
### Description

Save button stays grayed out.

### Steps to reproduce

1. Account Settings
2. Change Display Name
3. Save remains grayed out.

### Environment details

Operating System + Hardware details: Montery + 2019 MacBook Pro Inteli7
Telios Version: 0.9.612

### Expected behavior

Save button should no longer be disabled.

**Comment by Ellobo16** [comment]
Just tested this out on v0.9.630, and this seems to be addressed.
